doctrine:
    dbal:
        connections:
            itsm_sor:
                url: '%env(resolve:ITSM_SOR_DATABASE_URL)%'
    orm:
        entity_managers:
            itsm_sor:
                auto_mapping: false
                connection: itsm_sor
                mappings:
                    IstmSor:
                        type: attribute
                        is_bundle: false
                        dir: '%kernel.project_dir%/src/IstmSor/Entity'
                        prefix: 'App\IstmSor\Entity'
                        alias: IstmSor
